import "./App.css";
import "./style.css";

import { Header } from "./Header";
import { MusicPlayer } from "./MusicPlayer";
import Clock from "./Clock";
import { useState } from "react";

function App() {
  const [showClock, setShowClock] = useState(false);

  return (
    <>
      <div className="flex flex-col h-screen">
        <Header
          toggleClock={() => {
            setShowClock((t) => !t);
          }}
        />
        <div className="flex-1 flex flex-col lg:flex-row">
          <div className="bg-gray-70 flex w-full">
            <MusicPlayer allSongs={songs} />
          </div>
        </div>
      </div>
      {showClock && <Clock />}
    </>
  );
}

export default App;

const songs = [
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
  {
    name: "Neruppu Da",
    artist: "Kabali",
    duration: "3:38",
    current: 0,
    isNew: true,
    img: "kabali.jpg",
  },
  {
    name: "Lose My Breath",
    artist: "Stray Kids (ft Charlie Puth)",
    duration: "2:47",
    current: 0,
    isNew: true,
    img: "lose-my-breadth.jpg",
  },
  {
    name: "The Late Greats",
    artist: "Wilco",
    duration: "2:31",
    current: 0,
    isNew: true,
    img: "wilco.jpg",
  },
  {
    name: "Chaleya",
    artist: "Jawan",
    duration: "3:20",
    current: 0,
    isNew: false,
    img: "jawan.jpg",
  },
  {
    name: "Realiti",
    artist: "Grimes",
    duration: "5:06",
    current: 0,
    isNew: false,
    img: "grimes.png",
  },
  {
    name: "Mukkala Mukkabla",
    artist: "Kadhalan",
    duration: "5:23",
    current: 0,
    isNew: true,
    img: "kadhalan.jpeg",
  },
  {
    name: "夏の肖像",
    artist: "幻燈",
    duration: "5:25",
    current: 0,
    isNew: true,
    img: "yorushika.jpg",
  },
  {
    name: "Kun Faaya Kun",
    artist: "Rockstar",
    duration: "7:53",
    current: 0,
    isNew: true,
    img: "rockstar.jpg",
  },
  {
    name: "Strawberry Fields Forever",
    artist: "Magical Mystery Tour",
    duration: "4:05",
    current: 0,
    isNew: true,
    img: "beatles.jpg",
  },
  {
    name: "Mitwa",
    artist: "Lagaan",
    duration: "6:47",
    current: 0,
    isNew: true,
    img: "lagaan.jpeg",
  },
  {
    name: "Supermassive Black Hole",
    artist: "Muse",
    duration: "3:37",
    current: 0,
    isNew: true,
  },
  {
    name: "Mr. Brightside",
    artist: "Hot Fuss",
    duration: "3:43",
    current: 0,
    isNew: true,
    img: "killers.jpg",
  },
  {
    name: "Time Is Running Out",
    artist: "Muse",
    duration: "4:24",
    current: 0,
    isNew: true,
  },
];
